server:
  port: 8008
spring:
  datasource:
    url: 'jdbc:h2:mem:intellisoft'
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
